YingShiShuPing/urls.py
from django.conf.urls import include, url
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin

urlpatterns = [
    url(r'^main/', include('main.urls')),
    url(r'^books/', include('books.urls')),
    url(r'^admin/', admin.site.urls),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)   
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

books/urls.py
# -*- coding: utf-8 -*-

from django.conf.urls import url

from books import views

app_name = 'books'

urlpatterns = [
    url(r'^$', views.IndexView.as_view(), name='index'),
    url(r'^Add$', views.AddView.as_view(), name='add'),
    url(r'^Save/$', views.Save, name='save'),
    url(r'^(?P<pk>[0-9]+)/$', views.DetailView.as_view(), name='detail'),
]
        
        




main/urls.py
# -*- coding: utf-8 -*-

from django.conf.urls import url

from main import views

app_name = 'main'

urlpatterns = [
    url(r'^$', views.HomePageView, name='HomePageView'),
    url(r'^Search/$', views.Search, name='Search'),
    url(r'^SearchImage/$', views.SearchImage, name='SearchImage'),
]

books/models.py
from django.db import models

# Create your models here.
class Book(models.Model):
    book_name = models.CharField(max_length = 50)
    book_content = models.CharField(max_length = 255)
    book_image = models.ImageField(upload_to='books/image',null=True)
    book_image_R = models.PositiveIntegerField(default = 0)
    book_image_G = models.PositiveIntegerField(default = 0)
    book_image_B = models.PositiveIntegerField(default = 0)
    
    
#class Chapter(models.Model):
#    chapter_content = models.CharField(max_length = 500)

main/models.py
from django.db import models

# Create your models here.

books/views.py
from django.views import generic
from django.template import RequestContext
from django.views.generic import CreateView
from django.core.urlresolvers import reverse
from django.http import HttpResponse, HttpResponseRedirect
from .models import Book
from books.Book_Form import BookEntryForm
from PIL import Image

# Create your views here.
class IndexView(generic.ListView):
    template_name = 'books/index.html'
    context_object_name = 'book_list'
    
    def get_queryset(self):
        #return Book.objects.order_by('-book_name')[:5]
        return Book.objects.order_by('-id')
        
class DetailView(generic.DetailView):
    model = Book
    template_name = 'books/detail.html'
    #context_instance=RequestContext(request)
    
class AddView(CreateView):
    model = Book
    fields = ['book_name','book_content','book_image']
    template_name = 'books/add.html'
    
def Save(request):
    #p = Book.objects.create(book_name=request.FILES['book_name'], book_content="Springsteen")
    b = BookEntryForm(request.POST or None, request.FILES or None)
    if b.is_valid():
        b.save()
        im = Image.open( b.cleaned_data['book_image'])
        width, height = im.size
        pix = im.load()
        value = pix[width/2, height/2]
        bb = Book.objects.get(book_name=b.cleaned_data['book_name'])
        bb.book_image_R = value[0]
        bb.book_image_G = value[1]
        bb.book_image_B = value[2]
        bb.save()
        im.close()
    return HttpResponseRedirect(reverse('books:index'))

main/views.py
from django.views.generic.base import TemplateView
from django.shortcuts import render
from django.core.urlresolvers import reverse
from django.http import HttpResponse, HttpResponseRedirect
from django.template.response import TemplateResponse
from books.models import Book
from PIL import Image

from main.ImageUpload_Form1 import Image_Upload_Form1
    
def HomePageView(request):
    image_form = Image_Upload_Form1(request.POST or None, request.FILES or None)
    return render(request, 'main/index.html', {'image_form': image_form})


def Search(request):
    selected_book = Book.objects.get(book_name=request.POST['search_text'])
    return HttpResponseRedirect(reverse('books:detail',args=(selected_book.id,)))
    
def SearchImage(request):
    #uploaded_image = request.FILES['image']   # 'image' is the name of Image_Upload_Form1.image 
    im = Image.open( request.FILES['image'] )
    width, height = im.size
    pix = im.load()
    value = pix[width/2, height/2]
    R=value[0]
    G=value[1]
    B=value[2]
    im.close()
#    html = "<html><body>The color is (%(R)s,%(G)s,%(B)s).</body></html>" % {'R':value[0],'G':value[1],'B':value[2]}
    book_list =( Book.objects.filter(book_image_R__range=(R-50,R+50))
    .filter(book_image_G__range=(G-50,G+50))
    .filter(book_image_B__range=(B-50,B+50)))
    return render(request,'main/Search_result.html',{'book_list':book_list})

books/templates/books/add.html
<h1>Add Book</h1>

<form enctype="multipart/form-data" action="{% url 'books:save' %}" method="POST">
  {% csrf_token %}
  <ul>
    {{ form.as_p }}
  </ul>
  <input id="add_book" type="submit" value="Add" />
</form>

<a href="{% url 'books:index' %}">Books</a>

books/templates/books/detail.html
<!--{%load staticfiles%}-->

<a href="{% url 'books:index' %}">Books</a>

<hr>

<h1>{{ book.book_name }}</h1>

<h1>{{ book.book_content }}</h1>

<img src="{{ book.book_image.url }}" />

<!--<img src="{% static "_MG_4816.JPG"%}" />-->

books/templates/books/index.html
<!--{%load staticfiles%}-->

<a href="{% url 'main:HomePageView'  %}">Main</a>

{% if book_list %}
    <ul>
    {% for b in book_list %}
        <hr>
        <li><a href="{% url 'books:detail' b.id %}">{{ b.book_name }}</a></li>
        <img src="{{ b.book_image.url }}" width = "100" height = "100"/>
    {% endfor %}
    <hr>
    </ul>
{% else %}
    <p>No books are available.</p>
{% endif %}

main/templates/main/Search_result.html
<a href="{% url 'main:HomePageView'  %}">Main</a>

<li><a href="{% url 'books:index' %}">Books</a></li>

{% if book_list %}
    <ul>
    {% for b in book_list %}
        <hr>
        <li><a href="{% url 'books:detail' b.id %}">{{ b.book_name }}</a></li>
        <img src="{{ b.book_image.url }}" width = "100" height = "100"/>
    {% endfor %}
    <hr>
    </ul>
{% else %}
    <p>No books are available.</p>
{% endif %}

main/templates/main/index.html
<h1>YingShiShuPing/影视书评</h1>

<hr>

<form action="{% url 'main:Search' %}" method="post">{% csrf_token %}
    <p>Books:</p>
    <input name="search_text" type="text" value=""/>
    <input type="submit" value="Search"/>
</form>

<hr>

<li><a href="{% url 'books:add' %}">Add Books</a></li>

<hr>

<form enctype="multipart/form-data" action="{% url 'main:SearchImage' %}" method="post">{% csrf_token %}
    {{image_form.as_p}}
    <input type="submit" value="Search Image"/>
</form>

<hr>

<li><a href="{% url 'books:index' %}">Books</a></li>
